apiVersion: apps/v1 
kind: Deployment
metadata:
  name: demo-ui
spec: 
  selector:
    matchLabels:
      app: demo-ui
  replicas: 2
  template:
    metadata:
      labels:
        app: demo-ui
    spec:
      containers:
      - name: demo-ui
        image: gcr.io/roi-dtc-m2022-u219/external-image:v1.0.0
        env: 
        - name: SERVER
          value: "http://demo-service:8082"
        ports:
        - containerPort: 8080
            
        